version: "3"
services:
  kafka:
    hostname: 'kafka'
    image: 'bitnami/kafka:latest'
    ports:
      - '9097:9097'
      - '9095:9095'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9097,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9097,EXTERNAL://localhost:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT




# Для нескольких брокеров
# services:
#   kafka-0:
#     image: 'bitnami/kafka:latest'
#     ports:
#       - '9097:9097'
#       - '9095:9095'
#     networks:
#       - kafka-network
#     environment:
#       # KRaft settings
#       - KAFKA_CFG_NODE_ID=0
#       - KAFKA_CFG_PROCESS_ROLES=controller,broker
#       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093
#       - KAFKA_KRAFT_CLUSTER_ID=your-cluster-id
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9097,CONTROLLER://:9093,EXTERNAL://:9095
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9097,EXTERNAL://localhost:9095
#       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#     networks:
#       - kafka-network

#   kafka-1:
#     image: 'bitnami/kafka:latest'
#     ports:
#       - '9098:9098'
#       - '9096:9096'
#     networks:
#       - kafka-network
#     environment:
#       # KRaft settings
#       - KAFKA_CFG_NODE_ID=1
#       - KAFKA_CFG_PROCESS_ROLES=controller,broker
#       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093
#       - KAFKA_KRAFT_CLUSTER_ID=your-cluster-id
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9098,CONTROLLER://:9093,EXTERNAL://:9096
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9098,EXTERNAL://localhost:9096
#       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#     networks:
#       - kafka-network

# networks:
#   kafka-network:
#     driver: bridge
